### PR TITLE
Curly braces as of PHP 7.4 are deprecated for accessing arrays.

### PR DESCRIPTION
**Pull request by jbrahy**
https://wiki.php.net/rfc/deprecate_curly_braces_array_access

### CODE REVIEW

**Comment by jbrahy** [comment]
Adding PHP Comment stubs

**Comment by jbrahy** [comment]
Expanding abbreviations for easier readability.

**Comment by jim-parry** [comment]
You are mixing several sets of changes into one PR ... bad practice, in case some are ok and some are not. Each PR should address a single issue or type of enhancement.
You also need to GPG-sign your commits.
PRs are NOT for the master branch - they should always be for the develop branch!
Related to this, you should always use feature branches to prepare PRs.
Too many things wrong with this one, sorry.

**Comment by jbrahy** [comment]
ok, I'll sort them out. Thanks

**Comment by jbrahy** [comment]
I only see the master branch.

**Comment by jim-parry** [comment]
Ah - I see you are tryig to update the "framework" repo That is a read-only repo, bult from the "codeigniter4" repo.
It is build by the admin/release-framework script in the main repo, and files unique to it are found in "admin/framework".
Your intent is good, but you are going about it incorrectly :-/

**Pull request closed without merging**
